modules/mage2/ecommerce/routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Mage2 E commerce Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an mage2 user modules.
  | It's a breeze. Simply tell mage2 user module the URI it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

Route::middleware(['web'])
    ->namespace('Mage2\Ecommerce\Http\Controllers')
    ->group(function () {
        Route::get('/contact', ['as' => 'contact', 'uses' => 'HomeController@contact']);
        Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

        //* ***** START MAGE2 CATALOG FRONT ROUTES  *****  */
        Route::get('/categoria/{slug}', ['as' => 'category.view',
            'uses' => 'CategoryViewController@view', ]);
        Route::get('/producto/{slug}', ['as' => 'product.view',
            'uses' => 'ProductViewController@view', ]);
        Route::get('/product-search', ['as' => 'search.result',
            'uses' => 'SearchController@result', ]);

        //* ***** END MAGE2 CATEGORY FRONT ROUTES  *****  */

        //* ***** START MAGE2 CART FRONT ROUTES  *****  */
        Route::post('/carrito/agregar', ['as' => 'carrito.agregar', 'uses' => 'CartController@addToCart']);

        Route::get('/carrito', ['as' => 'carrito.mostrar', 'uses' => 'CartController@view']);
        Route::put('/carrito/{id}', ['as' => 'carrito.actualizar', 'uses' => 'CartController@update']);
        Route::get('/carrito/{id}/eliminar', ['as' => 'carrito.eliminar', 'uses' => 'CartController@destroy']);

        Route::get('/wishlist/add/{slug}', ['as' => 'wishlist.add', 'uses' => 'WishlistController@add']);
        Route::get('/my-account/wishlist', ['as' => 'wishlist.list', 'uses' => 'WishlistController@mylist']);
        Route::get('/wishlist/remove/{slug}', ['as' => 'wishlist.remove', 'uses' => 'WishlistController@destroy']);

        Route::get('/checkout', ['as' => 'checkout.index', 'uses' => 'CheckoutController@index']);

        Route::post('/get_code_discount', ['as' => 'get.code_discount', 'uses' => 'GiftCouponController@getCodeDiscount']);

        Route::get('/order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
        Route::get('/order/success/{id}', ['as' => 'order.success', 'uses' => 'OrderController@success']);

        Route::get('/my-account/order/list', ['as' => 'my-account.order.list', 'uses' => 'OrderController@myAccountOrderList']);
        Route::get('/my-account/order/{id}/view', ['as' => 'my-account.order.view', 'uses' => 'OrderController@myAccountOrderView']);

        Route::post('/tax-calculation', ['as' => 'tax.calculation', 'uses' => 'TaxRuleController@getTaxAmount']);

        Route::get('/password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'ResetPasswordController@showResetForm']);
        Route::post('/password/reset', ['as' => 'password.reset.token', 'uses' => 'ResetPasswordController@reset']);

        Route::get('/password/reset', ['as' => 'password.reset', 'uses' => 'ForgotPasswordController@showLinkRequestForm']);
        Route::post('/password/email', ['as' => 'password.email.post', 'uses' => 'ForgotPasswordController@sendResetLinkEmail']);

        Route::get('/register', ['as' => 'register', 'uses' => 'RegisterController@showRegistrationForm']);
        Route::post('/register', ['as' => 'register.post', 'uses' => 'RegisterController@register']);

        Route::post('/order', ['as' => 'order.place', 'uses' => 'OrderController@place']);

        Route::get('/page/{slug}', ['as' => 'page.show',
            'uses' => 'PageController@show',
        ]);

        Route::post('/subscribe', ['as' => 'subscribe.store',
                                    'uses' => 'SubscribeController@store',
                                ]);

        Route::post('/tax-calculation', ['as' => 'tax.calculation', 'uses' => 'TaxRuleController@getTaxAmount']);

        Route::post('/review', ['as' => 'review.store', 'uses' => 'ReviewController@store']);
    });

Route::middleware(['web', 'front.auth'])
    ->namespace('Mage2\Ecommerce\Http\Controllers')
    ->group(function () {
        Route::get('/my-account', ['as' => 'my-account.home', 'uses' => 'MyAccountController@home']);
        Route::get('/my-account/edit', ['as' => 'my-account.edit', 'uses' => 'MyAccountController@edit']);
        Route::post('/my-account/edit', ['as' => 'my-account.store', 'uses' => 'MyAccountController@store']);

        Route::get('/my-account/upload-image', ['as' => 'my-account.upload-image', 'uses' => 'MyAccountController@uploadImage']);
        Route::post('/my-account/upload-image', ['as' => 'my-account.upload-image.post', 'uses' => 'MyAccountController@uploadImagePost']);

        Route::get('/my-account/change-password', ['as' => 'my-account.change-password', 'uses' => 'MyAccountController@changePassword']);
        Route::post('/my-account/change-password', ['as' => 'my-account.change-password.post', 'uses' => 'MyAccountController@changePasswordPost']);

        Route::resource('/my-account/address', 'AddressController', ['as' => 'my-account']);

        Route::get('/order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
        Route::get('/order/success/{id}', ['as' => 'order.success', 'uses' => 'OrderController@success']);

        Route::get('/my-account/order/list', ['as' => 'my-account.order.list', 'uses' => 'OrderController@myAccountOrderList']);
        Route::get('/my-account/order/{id}/view', ['as' => 'my-account.order.view', 'uses' => 'OrderController@myAccountOrderView']);

        Route::get('/wishlist/add/{slug}', ['as' => 'wishlist.add', 'uses' => 'WishlistController@add']);
        Route::get('/my-account/wishlist', ['as' => 'wishlist.list', 'uses' => 'WishlistController@mylist']);
        Route::get('/wishlist/remove/{slug}', ['as' => 'wishlist.remove', 'uses' => 'WishlistController@destroy']);
    });

Route::middleware(['web'])
    ->prefix('admin')
    ->namespace('Mage2\Ecommerce\Http\Controllers\Admin')
    ->group(function () {
        Route::get('login', ['as' => 'admin.login', 'uses' => 'LoginController@loginForm']);
        Route::post('login', ['as' => 'admin.login.post', 'uses' => 'LoginController@login']);

        Route::get('logout', ['as' => 'admin.logout', 'uses' => 'LoginController@logout']);

        Route::get('password/reset/{token}', ['as' => 'admin.password.reset.token', 'uses' => 'ResetPasswordController@showResetForm']);
        Route::post('password/email', ['as' => 'admin.password.email.post', 'uses' => 'ForgotPasswordController@sendResetLinkEmail']);

        Route::post('password/reset', ['as' => 'admin.password.reset.token', 'uses' => 'ResetPasswordController@reset']);

        Route::get('password/reset', ['as' => 'admin.password.reset', 'uses' => 'ForgotPasswordController@showLinkRequestForm']);
    });

Route::middleware(['web', 'admin.auth', 'permission'])
    ->prefix('admin')
    ->namespace('Mage2\Ecommerce\Http\Controllers\Admin')
    ->group(function () {
        /**************** ATTRIBUTES ROUTES STARTS ****************/

        /**************** ATTRIBUTES ROUTES ENDS ****************/

        Route::post('option-combination-modal', [
            'uses' => 'OptionController@optionCombinationModal',
            'as' => 'admin.option.combination',
        ]);

        Route::post('edit-option-combination-modal', [
            'uses' => 'OptionController@editOptionCombinationModal',
            'as' => 'admin.option.combination.edit',
        ]);

        Route::post('option-combination-update', [
            'uses' => 'OptionController@optionCombinationUpdate',
            'as' => 'admin.product.option-combination.update',
        ]);

        Route::resource('property', 'PropertyController', ['as' => 'admin']);

        Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'DashboardController@index']);

        Route::resource('/role', 'RoleController', ['as' => 'admin']);

        Route::resource('product', 'ProductController', ['as' => 'admin']);
        Route::resource('category', 'CategoryController', ['as' => 'admin']);
        Route::resource('review', 'ReviewController', ['as' => 'admin']);

        Route::resource('/page', 'PageController', ['as' => 'admin']);
        Route::resource('/tax-group', 'TaxGroupController', ['as' => 'admin']);
        Route::resource('/tax-rule', 'TaxRuleController', ['as' => 'admin']);
        Route::resource('/country', 'CountryController', ['as' => 'admin']);
        Route::resource('/state', 'StateController', ['as' => 'admin']);

        Route::resource('/admin-user', 'AdminUserController', ['as' => 'admin']);
        Route::resource('review', 'ReviewController', ['as' => 'admin']);

        Route::post('/product-attribute-panel', ['as' => 'admin.product-attribute.get-attribute', 'uses' => 'AttributeController@getAttribute']);

        Route::resource('/attribute', 'AttributeController', ['as' => 'admin']);

        Route::get('/admin-user-api-show', ['as' => 'admin.admin-user.show.api', 'uses' => 'AdminUserController@apiShow']);

        Route::post('product-image/upload', ['as' => 'admin.product.upload-image',
            'uses' => 'ProductController@uploadImage', ]);
        Route::post('product-image/delete', ['as' => 'admin.product.delete-image',
            'uses' => 'ProductController@deleteImage', ]);

        Route::resource('gift-coupon', 'GiftCouponController', ['as' => 'admin']);

        //Route::get('update-check', ['as' => 'admin.update.check', 'uses' => 'UpdateController@check']);

        Route::get('configuration', ['as' => 'admin.configuration', 'uses' => 'ConfigurationController@index']);
        Route::post('configuration', ['as' => 'admin.configuration.store', 'uses' => 'ConfigurationController@store']);

        Route::get('themes', ['as' => 'admin.theme.index', 'uses' => 'ThemeController@index']);

modules/mage2/ecommerce/resources/views/admin/gift-coupon/_fields.blade.php
@include('mage2-ecommerce::forms.text',['name' => 'name', 'label' => 'Name'])
@include('mage2-ecommerce::forms.text',['name' => 'code', 'label' => 'Code'])
@include('mage2-ecommerce::forms.text',['name' => 'discount', 'label' => 'Discount %'])
@include('mage2-ecommerce::forms.date',['name' => 'start_date', 'label' => 'Start Date'])
@include('mage2-ecommerce::forms.date',['name' => 'end_date', 'label' => 'End Date'])

@include('mage2-ecommerce::forms.select',['name' => 'status', 'label' => 'Status','options' => ['ENABLED' => 'Enabled','DISABLED' => 'Disabled']])

modules/mage2/ecommerce/resources/views/admin/gift-coupon/create.blade.php
@extends('mage2-ecommerce::admin.layouts.app')

@section('content')
    <div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">Create Gift Coupon</div>
                <div class="card-body">


                    <form action="{{ route('admin.gift-coupon.store') }}" method="post">
                        {{ csrf_field() }}
                    @include('mage2-ecommerce::admin.gift-coupon._fields')

                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Create Gift Coupon</button>
                        <a href="{{ route('admin.gift-coupon.index') }}" class="btn">Cancel</a>
                    </div>

                  </form>

                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

modules/mage2/ecommerce/resources/views/admin/gift-coupon/edit.blade.php
@extends('mage2-ecommerce::admin.layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    Edit Gift Coupon</div>
                <div class="card-body">

                    <form action="{{ route('admin.gift-coupon.update', $model->id) }}" method="post">
                    {{ csrf_field() }}
                        <input type="hidden" name="_method" value="put">
                        @include('mage2-ecommerce::admin.gift-coupon._fields')

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Update Gift Coupon</button>
                            <a href="{{ route('admin.gift-coupon.index') }}" class="btn">Cancel</a>
                        </div>
                    </form>


                </div>
            </div>

        </div>
    </div>
@endsection

modules/mage2/ecommerce/resources/views/admin/gift-coupon/index.blade.php
@extends('mage2-ecommerce::admin.layouts.app')

@section('content')
    <div class="container">
        <div class="h1">
            Gift Coupon List
            <a style="" href="{{ route('admin.gift-coupon.create') }}" class="btn btn-primary float-right">Create
                Gift Coupon</a>
        </div>

        {!! $dataGrid->render() !!}
    </div>
@stop