modules/mage2/ecommerce/routes/web.php
        Route::get('/checkout', ['as' => 'checkout.index', 'uses' => 'CheckoutController@index']);

        Route::post('/get_code_discount', ['as' => 'get.code_discount', 'uses' => 'GiftCouponController@getCodeDiscount']);

        Route::get('/order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
        Route::get('/order/success/{id}', ['as' => 'order.success', 'uses' => 'OrderController@success']);

        Route::get('/my-account/order/list', ['as' => 'my-account.order.list', 'uses' => 'OrderController@myAccountOrderList']);
        Route::get('/my-account/order/{id}/view', ['as' => 'my-account.order.view', 'uses' => 'OrderController@myAccountOrderView']);

        Route::post('/tax-calculation', ['as' => 'tax.calculation', 'uses' => 'TaxRuleController@getTaxAmount']);

        Route::get('/password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'ResetPasswordController@showResetForm']);
        Route::post('/password/reset', ['as' => 'password.reset.token', 'uses' => 'ResetPasswordController@reset']);

        Route::get('/password/reset', ['as' => 'password.reset', 'uses' => 'ForgotPasswordController@showLinkRequestForm']);
        Route::post('/password/email', ['as' => 'password.email.post', 'uses' => 'ForgotPasswordController@sendResetLinkEmail']);

        Route::get('/register', ['as' => 'register', 'uses' => 'RegisterController@showRegistrationForm']);
        Route::post('/register', ['as' => 'register.post', 'uses' => 'RegisterController@register']);

        Route::post('/order', ['as' => 'order.place', 'uses' => 'OrderController@place']);

        Route::get('/page/{slug}', ['as' => 'page.show',
            'uses' => 'PageController@show',
        ]);

        Route::post('/subscribe', ['as' => 'subscribe.store',
                                    'uses' => 'SubscribeController@store',
                                ]);

        Route::post('/tax-calculation', ['as' => 'tax.calculation', 'uses' => 'TaxRuleController@getTaxAmount']);

        Route::post('/review', ['as' => 'review.store', 'uses' => 'ReviewController@store']);
    });

Route::middleware(['web', 'front.auth'])
    ->namespace('Mage2\Ecommerce\Http\Controllers')
    ->group(function () {
        Route::get('/my-account', ['as' => 'my-account.home', 'uses' => 'MyAccountController@home']);
        Route::get('/my-account/edit', ['as' => 'my-account.edit', 'uses' => 'MyAccountController@edit']);
        Route::post('/my-account/edit', ['as' => 'my-account.store', 'uses' => 'MyAccountController@store']);

        Route::get('/my-account/upload-image', ['as' => 'my-account.upload-image', 'uses' => 'MyAccountController@uploadImage']);
        Route::post('/my-account/upload-image', ['as' => 'my-account.upload-image.post', 'uses' => 'MyAccountController@uploadImagePost']);

        Route::get('/my-account/change-password', ['as' => 'my-account.change-password', 'uses' => 'MyAccountController@changePassword']);
        Route::post('/my-account/change-password', ['as' => 'my-account.change-password.post', 'uses' => 'MyAccountController@changePasswordPost']);

        Route::resource('/my-account/address', 'AddressController', ['as' => 'my-account']);

        Route::get('/order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
        Route::get('/order/success/{id}', ['as' => 'order.success', 'uses' => 'OrderController@success']);

        Route::get('/my-account/order/list', ['as' => 'my-account.order.list', 'uses' => 'OrderController@myAccountOrderList']);
        Route::get('/my-account/order/{id}/view', ['as' => 'my-account.order.view', 'uses' => 'OrderController@myAccountOrderView']);

        Route::get('/wishlist/add/{slug}', ['as' => 'wishlist.add', 'uses' => 'WishlistController@add']);
        Route::get('/my-account/wishlist', ['as' => 'wishlist.list', 'uses' => 'WishlistController@mylist']);
        Route::get('/wishlist/remove/{slug}', ['as' => 'wishlist.remove', 'uses' => 'WishlistController@destroy']);
    });

Route::middleware(['web'])
    ->prefix('admin')
    ->namespace('Mage2\Ecommerce\Http\Controllers\Admin')
    ->group(function () {
        Route::get('login', ['as' => 'admin.login', 'uses' => 'LoginController@loginForm']);
        Route::post('login', ['as' => 'admin.login.post', 'uses' => 'LoginController@login']);

        Route::get('logout', ['as' => 'admin.logout', 'uses' => 'LoginController@logout']);

        Route::get('password/reset/{token}', ['as' => 'admin.password.reset.token', 'uses' => 'ResetPasswordController@showResetForm']);
        Route::post('password/email', ['as' => 'admin.password.email.post', 'uses' => 'ForgotPasswordController@sendResetLinkEmail']);

        Route::post('password/reset', ['as' => 'admin.password.reset.token', 'uses' => 'ResetPasswordController@reset']);

        Route::get('password/reset', ['as' => 'admin.password.reset', 'uses' => 'ForgotPasswordController@showLinkRequestForm']);
    });

Route::middleware(['web', 'admin.auth', 'permission'])
    ->prefix('admin')
    ->namespace('Mage2\Ecommerce\Http\Controllers\Admin')
    ->group(function () {
        /**************** ATTRIBUTES ROUTES STARTS ****************/

        /**************** ATTRIBUTES ROUTES ENDS ****************/

        Route::post('option-combination-modal', [
            'uses' => 'OptionController@optionCombinationModal',
            'as' => 'admin.option.combination',
        ]);

        Route::post('edit-option-combination-modal', [
            'uses' => 'OptionController@editOptionCombinationModal',
            'as' => 'admin.option.combination.edit',
        ]);

        Route::post('option-combination-update', [
            'uses' => 'OptionController@optionCombinationUpdate',
            'as' => 'admin.product.option-combination.update',
        ]);

        Route::resource('property', 'PropertyController', ['as' => 'admin']);

        Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'DashboardController@index']);

        Route::resource('/role', 'RoleController', ['as' => 'admin']);

        Route::resource('product', 'ProductController', ['as' => 'admin']);
        Route::resource('category', 'CategoryController', ['as' => 'admin']);
        Route::resource('review', 'ReviewController', ['as' => 'admin']);

        Route::resource('/page', 'PageController', ['as' => 'admin']);
        Route::resource('/tax-group', 'TaxGroupController', ['as' => 'admin']);
        Route::resource('/tax-rule', 'TaxRuleController', ['as' => 'admin']);
        Route::resource('/country', 'CountryController', ['as' => 'admin']);
        Route::resource('/state', 'StateController', ['as' => 'admin']);

        Route::resource('/admin-user', 'AdminUserController', ['as' => 'admin']);
        Route::resource('review', 'ReviewController', ['as' => 'admin']);

        Route::post('/product-attribute-panel', ['as' => 'admin.product-attribute.get-attribute', 'uses' => 'AttributeController@getAttribute']);

        Route::resource('/attribute', 'AttributeController', ['as' => 'admin']);

        Route::get('/admin-user-api-show', ['as' => 'admin.admin-user.show.api', 'uses' => 'AdminUserController@apiShow']);

        Route::post('product-image/upload', ['as' => 'admin.product.upload-image',
            'uses' => 'ProductController@uploadImage', ]);
        Route::post('product-image/delete', ['as' => 'admin.product.delete-image',
            'uses' => 'ProductController@deleteImage', ]);

        Route::resource('gift-coupon', 'GiftCouponController', ['as' => 'admin']);

        //Route::get('update-check', ['as' => 'admin.update.check', 'uses' => 'UpdateController@check']);

        Route::get('configuration', ['as' => 'admin.configuration', 'uses' => 'ConfigurationController@index']);
        Route::post('configuration', ['as' => 'admin.configuration.store', 'uses' => 'ConfigurationController@store']);

        Route::get('themes', ['as' => 'admin.theme.index', 'uses' => 'ThemeController@index']);

        Route::get('themes/create', ['as' => 'admin.theme.create', 'uses' => 'ThemeController@create']);
        Route::post('themes', ['as' => 'admin.theme.store', 'uses' => 'ThemeController@store']);

        Route::post('active-themes/{name}', ['as' => 'admin.theme.activated', 'uses' => 'ThemeController@activated']);

        Route::post('deactive-themes/{name}', ['as' => 'admin.theme.deactivated', 'uses' => 'ThemeController@deactivated']);

        Route::delete('themes/{name}', ['as' => 'admin.theme.destroy', 'uses' => 'ThemeController@destroy']);

        Route::resource('order-status', 'OrderStatusController', ['as' => 'admin']);

        Route::resource('subscriber', 'SubscriberController', ['as' => 'admin']);

        Route::get('order', [
                'as' => 'admin.order.index',
                'uses' => 'OrderController@index',
        ]);

        Route::post('get-property-element', [
            'as' => 'admin.property.element',
            'uses' => 'PropertyController@getElementHtml',
        ]);

        Route::post('edit-product-variation', [
            'as' => 'admin.variation.edit',
            'uses' => 'ProductController@editVariation',
        ]);

        Route::post('get-attribute-element', [
            'as' => 'admin.attribute.element',
            'uses' => 'AttributeController@getElementHtml',
        ]);

        Route::get('order/{id}', ['as' => 'admin.order.view', 'uses' => 'OrderController@view']);
        Route::get('order/{id}/send-email-invoice', ['as' => 'admin.order.send-email-invoice', 'uses' => 'OrderController@sendEmailInvoice']);

        Route::get('order/{id}/change-status', ['as' => 'admin.order.change-status', 'uses' => 'OrderController@changeStatus']);
        Route::put('order/{id}/update-status', ['as' => 'admin.order.update-status', 'uses' => 'OrderController@updateStatus']);

        /*
        Route::get('related-product-get-datatable-data/{id?}',

modules/mage2/ecommerce/resources/views/admin/state/_fields.blade.php
@include('mage2-ecommerce::forms.select',['name' => 'country_id','label' => "Country", 'options' => $countryOptions])

@include('mage2-ecommerce::forms.text',['name' => 'name','label' => "Name"])

@include('mage2-ecommerce::forms.text',['name' => 'code','label' => "Code"])

modules/mage2/ecommerce/resources/views/admin/state/create.blade.php
@extends('mage2-ecommerce::admin.layouts.app')

@section('content')
    <div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    Create State
                    <!--<small>Sub title</small> -->
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.state.store') }}" method="post">
                    {{ csrf_field() }}


                    @include('mage2-ecommerce::admin.state._fields')

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Create State</button>
                            <a href="{{ route('admin.state.index') }}" class="btn">Cancel</a>
                        </div>

                    </form>

                </div>
            </div>

        </div>
    </div>
    </div>
@endsection

modules/mage2/ecommerce/resources/views/admin/state/edit.blade.php
@extends('mage2-ecommerce::admin.layouts.app')

@section('content')
    <div class="container">
    <div class="row">
        <div class=" col-12">
            <div class="card">
                <div class="card-header">
                    Edit State
                    <!--<small>Sub title</small> -->
                </div>

                <div class="card-body">
                    <form action="{{ route('admin.state.update', $model->id) }}" method="post">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="put">

                        @include('mage2-ecommerce::admin.state._fields')

                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Update State</button>
                        <a href="{{ route('admin.state.index') }}" class="btn">Cancel</a>
                    </div>

                    </form>

                </div>
            </div>

        </div>
    </div>
    </div>
@endsection

modules/mage2/ecommerce/resources/views/admin/state/index.blade.php
@extends('mage2-ecommerce::admin.layouts.app')

@section('content')
    <div class="container">
        <div class="h1">
            State List
            <a style="" href="{{ route('admin.state.create') }}" class="btn btn-primary float-right">Create
                State</a>
        </div>
        {!! $dataGrid->render() !!}
    </div>
@stop