modules/mage2/ecommerce/routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Mage2 E commerce Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an mage2 user modules.
  | It's a breeze. Simply tell mage2 user module the URI it should respond to
  | and give it the controller to call when that URI is requested.
  |
 */

Route::middleware(['web'])
    ->namespace('Mage2\Ecommerce\Http\Controllers')
    ->group(function () {
        Route::get('/contact', ['as' => 'contact', 'uses' => 'HomeController@contact']);
        Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

        //* ***** START MAGE2 CATALOG FRONT ROUTES  *****  */
        Route::get('/categoria/{slug}', ['as' => 'category.view',
            'uses' => 'CategoryViewController@view', ]);
        Route::get('/producto/{slug}', ['as' => 'product.view',
            'uses' => 'ProductViewController@view', ]);
        Route::get('/product-search', ['as' => 'search.result',
            'uses' => 'SearchController@result', ]);

        //* ***** END MAGE2 CATEGORY FRONT ROUTES  *****  */

        //* ***** START MAGE2 CART FRONT ROUTES  *****  */
        Route::post('/carrito/agregar', ['as' => 'carrito.agregar', 'uses' => 'CartController@addToCart']);

        Route::get('/carrito', ['as' => 'carrito.mostrar', 'uses' => 'CartController@view']);
        Route::put('/carrito/{id}', ['as' => 'carrito.actualizar', 'uses' => 'CartController@update']);
        Route::get('/carrito/{id}/eliminar', ['as' => 'carrito.eliminar', 'uses' => 'CartController@destroy']);

        Route::get('/wishlist/add/{slug}', ['as' => 'wishlist.add', 'uses' => 'WishlistController@add']);
        Route::get('/my-account/wishlist', ['as' => 'wishlist.list', 'uses' => 'WishlistController@mylist']);
        Route::get('/wishlist/remove/{slug}', ['as' => 'wishlist.remove', 'uses' => 'WishlistController@destroy']);

        Route::get('/checkout', ['as' => 'checkout.index', 'uses' => 'CheckoutController@index']);

        Route::post('/get_code_discount', ['as' => 'get.code_discount', 'uses' => 'GiftCouponController@getCodeDiscount']);

        Route::get('/order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
        Route::get('/order/success/{id}', ['as' => 'order.success', 'uses' => 'OrderController@success']);

        Route::get('/my-account/order/list', ['as' => 'my-account.order.list', 'uses' => 'OrderController@myAccountOrderList']);
        Route::get('/my-account/order/{id}/view', ['as' => 'my-account.order.view', 'uses' => 'OrderController@myAccountOrderView']);

        Route::post('/tax-calculation', ['as' => 'tax.calculation', 'uses' => 'TaxRuleController@getTaxAmount']);

        Route::get('/password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'ResetPasswordController@showResetForm']);
        Route::post('/password/reset', ['as' => 'password.reset.token', 'uses' => 'ResetPasswordController@reset']);

        Route::get('/password/reset', ['as' => 'password.reset', 'uses' => 'ForgotPasswordController@showLinkRequestForm']);
        Route::post('/password/email', ['as' => 'password.email.post', 'uses' => 'ForgotPasswordController@sendResetLinkEmail']);

        Route::get('/register', ['as' => 'register', 'uses' => 'RegisterController@showRegistrationForm']);
        Route::post('/register', ['as' => 'register.post', 'uses' => 'RegisterController@register']);

        Route::post('/order', ['as' => 'order.place', 'uses' => 'OrderController@place']);

        Route::get('/page/{slug}', ['as' => 'page.show',
            'uses' => 'PageController@show',
        ]);

        Route::post('/subscribe', ['as' => 'subscribe.store',
                                    'uses' => 'SubscribeController@store',
                                ]);

        Route::post('/tax-calculation', ['as' => 'tax.calculation', 'uses' => 'TaxRuleController@getTaxAmount']);

        Route::post('/review', ['as' => 'review.store', 'uses' => 'ReviewController@store']);
    });

Route::middleware(['web', 'front.auth'])
    ->namespace('Mage2\Ecommerce\Http\Controllers')
    ->group(function () {
        Route::get('/my-account', ['as' => 'my-account.home', 'uses' => 'MyAccountController@home']);
        Route::get('/my-account/edit', ['as' => 'my-account.edit', 'uses' => 'MyAccountController@edit']);
        Route::post('/my-account/edit', ['as' => 'my-account.store', 'uses' => 'MyAccountController@store']);

        Route::get('/my-account/upload-image', ['as' => 'my-account.upload-image', 'uses' => 'MyAccountController@uploadImage']);
        Route::post('/my-account/upload-image', ['as' => 'my-account.upload-image.post', 'uses' => 'MyAccountController@uploadImagePost']);

        Route::get('/my-account/change-password', ['as' => 'my-account.change-password', 'uses' => 'MyAccountController@changePassword']);
        Route::post('/my-account/change-password', ['as' => 'my-account.change-password.post', 'uses' => 'MyAccountController@changePasswordPost']);

        Route::resource('/my-account/address', 'AddressController', ['as' => 'my-account']);

        Route::get('/order', ['as' => 'order.index', 'uses' => 'OrderController@index']);
        Route::get('/order/success/{id}', ['as' => 'order.success', 'uses' => 'OrderController@success']);

        Route::get('/my-account/order/list', ['as' => 'my-account.order.list', 'uses' => 'OrderController@myAccountOrderList']);
        Route::get('/my-account/order/{id}/view', ['as' => 'my-account.order.view', 'uses' => 'OrderController@myAccountOrderView']);

        Route::get('/wishlist/add/{slug}', ['as' => 'wishlist.add', 'uses' => 'WishlistController@add']);
        Route::get('/my-account/wishlist', ['as' => 'wishlist.list', 'uses' => 'WishlistController@mylist']);
        Route::get('/wishlist/remove/{slug}', ['as' => 'wishlist.remove', 'uses' => 'WishlistController@destroy']);
    });

Route::middleware(['web'])
    ->prefix('admin')
    ->namespace('Mage2\Ecommerce\Http\Controllers\Admin')
    ->group(function () {
        Route::get('login', ['as' => 'admin.login', 'uses' => 'LoginController@loginForm']);
        Route::post('login', ['as' => 'admin.login.post', 'uses' => 'LoginController@login']);

        Route::get('logout', ['as' => 'admin.logout', 'uses' => 'LoginController@logout']);

        Route::get('password/reset/{token}', ['as' => 'admin.password.reset.token', 'uses' => 'ResetPasswordController@showResetForm']);
        Route::post('password/email', ['as' => 'admin.password.email.post', 'uses' => 'ForgotPasswordController@sendResetLinkEmail']);

        Route::post('password/reset', ['as' => 'admin.password.reset.token', 'uses' => 'ResetPasswordController@reset']);

        Route::get('password/reset', ['as' => 'admin.password.reset', 'uses' => 'ForgotPasswordController@showLinkRequestForm']);
    });

Route::middleware(['web', 'admin.auth', 'permission'])
    ->prefix('admin')
    ->namespace('Mage2\Ecommerce\Http\Controllers\Admin')
    ->group(function () {
        /**************** ATTRIBUTES ROUTES STARTS ****************/

        /**************** ATTRIBUTES ROUTES ENDS ****************/

        Route::post('option-combination-modal', [
            'uses' => 'OptionController@optionCombinationModal',
            'as' => 'admin.option.combination',
        ]);

        Route::post('edit-option-combination-modal', [
            'uses' => 'OptionController@editOptionCombinationModal',
            'as' => 'admin.option.combination.edit',
        ]);

        Route::post('option-combination-update', [
            'uses' => 'OptionController@optionCombinationUpdate',
            'as' => 'admin.product.option-combination.update',
        ]);

        Route::resource('property', 'PropertyController', ['as' => 'admin']);

        Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'DashboardController@index']);

        Route::resource('/role', 'RoleController', ['as' => 'admin']);

        Route::resource('product', 'ProductController', ['as' => 'admin']);
        Route::resource('category', 'CategoryController', ['as' => 'admin']);
        Route::resource('review', 'ReviewController', ['as' => 'admin']);

        Route::resource('/page', 'PageController', ['as' => 'admin']);
        Route::resource('/tax-group', 'TaxGroupController', ['as' => 'admin']);
        Route::resource('/tax-rule', 'TaxRuleController', ['as' => 'admin']);
        Route::resource('/country', 'CountryController', ['as' => 'admin']);
        Route::resource('/state', 'StateController', ['as' => 'admin']);

        Route::resource('/admin-user', 'AdminUserController', ['as' => 'admin']);
        Route::resource('review', 'ReviewController', ['as' => 'admin']);

        Route::post('/product-attribute-panel', ['as' => 'admin.product-attribute.get-attribute', 'uses' => 'AttributeController@getAttribute']);

        Route::resource('/attribute', 'AttributeController', ['as' => 'admin']);

        Route::get('/admin-user-api-show', ['as' => 'admin.admin-user.show.api', 'uses' => 'AdminUserController@apiShow']);

        Route::post('product-image/upload', ['as' => 'admin.product.upload-image',
            'uses' => 'ProductController@uploadImage', ]);
        Route::post('product-image/delete', ['as' => 'admin.product.delete-image',
            'uses' => 'ProductController@deleteImage', ]);

        Route::resource('gift-coupon', 'GiftCouponController', ['as' => 'admin']);

        //Route::get('update-check', ['as' => 'admin.update.check', 'uses' => 'UpdateController@check']);

        Route::get('configuration', ['as' => 'admin.configuration', 'uses' => 'ConfigurationController@index']);
        Route::post('configuration', ['as' => 'admin.configuration.store', 'uses' => 'ConfigurationController@store']);

        Route::get('themes', ['as' => 'admin.theme.index', 'uses' => 'ThemeController@index']);

modules/mage2/ecommerce/resources/views/admin/product/card/attribute.blade.php
<?php
$productVariations = $model->productVariations;
$productAttributes = $model->getProductAllAttributes();
?>


<div class="row">

    <div class="col-12">


        @if($attributeOptions !== null && $attributeOptions->count() >= 0)

            <div class="input-group mb-3">

                <select class="select2 attribute-dropdown-element  form-control" multiple name="attribute_selected[]"
                        style="width: 80%">
                    @foreach($attributeOptions as $value => $label)
                        <option
                                @if($productAttributes->contains('attribute_id',$value))
                                selected
                                @endif

                                value="{{ $value }}">{{ $label }}</option>
                    @endforeach
                </select>

                <div class="input-group-append">
                    <button data-token="{{ csrf_token() }}" data-product-id="{{ $model->id }}"
                            class="btn btn-warning use-selected-attribute"
                            type="button">Use Selected
                    </button>
                </div>

            </div>

            <div class="product-variation-card-wrapper   row"></div>



            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Destroy</th>


                </tr>
                </thead>
                <tbody>
                @foreach($model->variations as $variation)
                <tr>
                    <th scope="row">{{ $variation->variationProduct->id }}</th>
                    <td>{{ $variation->variationProduct->name }}</td>
                    <td>{{ $variation->variationProduct->price }}</td>
                    <td>{{ $variation->variationProduct->qty }}</td>
                    <td>
                        <a href="#"
                           data-token="{{ csrf_token() }}"
                           class="edit-variation-link"
                           data-variation-id="{{ $variation->variationProduct->id }}">
                            Edit
                        </a>
                    </td>
                    <td>
                        <a href="#" onclick="event.preventDefault();
                                             document.getElementById('product-variation-{{ $variation->variationProduct->id }}').submit();">
                            Destroy
                        </a>
                        <form id="product-variation-{{ $variation->variationProduct->id }}" action="{{ route('admin.product.destroy', $variation->variationProduct->id) }}"
                              method="POST" style="display: none;">
                            <input type="hidden" name="_method" value="delete">
                            {{ csrf_field() }}
                        </form>
                    </td>
                </tr>
                @endforeach

                </tbody>

            </table>

        @endif
    </div>

</div>


@push('scripts')
    <script>
        $(function () {


            jQuery(document).on('click','.edit-variation-link',function (e) {
                e.preventDefault();
                e.stopPropagation();

                var variationId = jQuery(this).attr('data-variation-id');

                if(jQuery('#variation-modal-' + variationId).length > 0) {

                    jQuery('#variation-modal-' + variationId).modal();

                } else {

                    var data = {_token: jQuery(this).attr('data-token'), variation_id: variationId};
                    jQuery.ajax({
                        url: '{{ route('admin.variation.edit') }}',
                        data: data,
                        method: 'post',
                        dataType: 'json',
                        success: function (response) {

                            if (response.success == true) {

                                jQuery(document.body).append(response.content);
                                jQuery(response.modalId).modal();
                            }
                        }
                    });
                }


            })
            jQuery(document).on('click', '.remove-option', function (e) {
                e.preventDefault();
                e.stopPropagation();
                if (jQuery(this).parents('.option-tag-list:first').find('.single-option').length > 1) {
                    jQuery(this).parents(".single-option:first").remove();
                } else {
                    alert('You cannot remove all possible Options');
                }
            });
            jQuery('.use-selected-attribute').click(function (e) {
                e.preventDefault();
                e.stopPropagation();
                var elementValue = jQuery('.attribute-dropdown-element').val();
                var productId = jQuery(this).attr('data-product-id');
                var data = {_token: jQuery(this).attr('data-token'), attribute_id: elementValue, product_id: productId};
                jQuery.ajax({
                    url: '{{ route('admin.attribute.element') }}',
                    data: data,
                    method: 'post',
                    dataType: 'json',
                    success: function (response) {
                        if (response.success == true) {
                            jQuery('.product-variation-card-wrapper').html(response.content);
                            jQuery('.product-variation-wrapper').toggleClass('d-none');
                        }
                    }
                });
            });


        });


    </script>

@endpush

modules/mage2/ecommerce/resources/views/admin/product/card/basic.blade.php
<div class="row">
    <div class="col-6">
        @include('mage2-ecommerce::forms.text',['name' => 'name','label' => 'Name'])
    </div>
    <div class="col-6">
        @if(!isset($productCategories))
            <?php $productCategories = []; ?>
        @endif

            @include('mage2-ecommerce::forms.select2',['name' => 'category_id[]',
                                                    'label' => 'Category',
                                                    'attributes' => ['class' => 'form-control select2',
                                                                    'id' => 'category_id',
                                                                    'multiple' => true,
                                                                    ],
                                                    'options' => $categoryOptions,
                                                    'values' => $productCategories])


    </div>
</div>


<div class="row">
    <div class="col-6">
        @if(isset($editMethod) && $editMethod)
            @include('mage2-ecommerce::forms.text',['name' => 'slug','label' => 'Slug'])
        @endif
    </div>
    <div class="col-6">
        @include('mage2-ecommerce::forms.text',['name' => 'sku','label' => 'Sku'])
    </div>
</div>

@include('mage2-ecommerce::forms.textarea',['name' => 'description','label' => 'Description',
                                            'attributes' => ['class' => 'summernote','id' => 'description']])

<div class="row">
    @if($model->type == "VARIATION")
    <div class="col-6">
        @include('mage2-ecommerce::forms.text',['name' => 'price','label' => 'Base Price'])
    </div>
    @else
        <div class="col-6">
            @include('mage2-ecommerce::forms.text',['name' => 'price','label' => 'Price'])
        </div>
    @endif
    <div class="col-6">
            @include('mage2-ecommerce::forms.text',['name' => 'qty','label' => 'Qty'])
        
        {{--  @include('mage2-ecommerce::forms.select',['name' => 'status','label' => 'Status', 'options' => ['1' => 'Enabled','0' => 'Disabled']])  --}}
        <input type="hidden" value="1" name="status"></input>
        
    </div>
</div>


<div class="row">
    <div class="col-6">
        {{--  @include('mage2-ecommerce::forms.text',['name' => 'qty','label' => 'Qty'])  --}}
    </div>
    <div class="col-6">
        {{--  @include('mage2-ecommerce::forms.select',['name' => 'in_stock','label' => 'In Stock', 'options' => ['1' => 'Enabled','0' => 'Disabled']])  --}}
        <input type="hidden" value="1" name="in_stock"></input>
    </div>
</div>

<div class="row">
    <div class="col-6">
        {{--  @include('mage2-ecommerce::forms.select',['name' => 'track_stock','label' => 'Track Stock', 'options' => ['1' => 'Enabled','0' => 'Disabled']])  --}}
        <input type="hidden" value="1" name="track_stock"></input>

    </div>
    <div class="col-6">
        {{--  @include('mage2-ecommerce::forms.select',['name' => 'is_taxable','label' => 'Is taxable', 'options' => ['1' => 'Enabled','0' => 'Disabled']])  --}}
        <input type="hidden" value="1" name="is_taxable"></input>        
    </div>
</div>

@foreach(Attributes::all('basic-product') as $attribute)
    <?php

    ?>
    {!! $attribute->render() !!}
@endforeach

@push('scripts')

    <script>

        $('.summernote').summernote({
        });

    </script>


@endpush

modules/mage2/ecommerce/resources/views/admin/product/card/images.blade.php
<input type="file" class="product-image-element form-control" data-token="{{ csrf_token() }}"
        >

<div class="product-image-list">

    @if(isset($model) && $model->images()->get()->count() > 0)
        @foreach($model->images()->get() as $image)
            <?php $class = ($image->is_main_image == 1) ? "active" : ""; ?>
            <div class="image-preview">
                <div class="actual-image-thumbnail">
                     @if(file_exists( public_path(). $image->path->relativePath))
                    <img class="img-thumbnail img-tag img-responsive" src="{{$image->path->smallUrl}}"/>
                    @else
                    <img class="img-thumbnail img-tag img-responsive" src="{{ asset('img/enlace-roto.png') }}"/>
                    @endif
                    <input type="hidden" name="image[{{ $image->id }}][path]" value="{{ $image->path->relativePath }}"/>
                    @if($image->is_main_image)
                        <input type="hidden" class="is_main_image_hidden_field"
                               name="image[{{ $image->id }}][is_main_image]" value="1"/>
                    @else
                        <input type="hidden" class="is_main_image_hidden_field"
                               name="image[{{ $image->id }}][is_main_image]" value="0"/>
                    @endif
                </div>
                <div class="image-info">
                    <div class="image-title">
                        {{ $image->name }}
                    </div>
                    <div class="actions">
                        <div class="action-buttons pull-right">

                            <button type="button"
                                    class="btn is_main_image_button {{ $class }} selected-icon"
                                    title="Select as Main Image">
                                <i class="fas fa-check-square"></i>
                            </button>
                            <button type="button" class="destroy-image btn btn-xs btn-default" title="Remove file">
                                <i class="fas fa-trash-alt text-danger"></i>
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        @endforeach
    @endif
</div>
@push('styles')
<style>

    .image-preview {
        position: relative;
        display: table;
        margin: 8px;
        border: 1px solid #ddd;
        box-shadow: 1px 1px 5px 0 #a2958a;
        padding: 6px;
        float: left;
        text-align: center;
    }

    .image-preview .actual-image-thumbnail {
        height: 170px;
    }

    .image-preview .image-info .active.selected-icon {
        color: #00dd00;
    }

    .image-preview .image-info .image-title {
        margin-bottom: 15px;
    }

    .image-preview .image-info {
        position: relative;
        height: 70px;
    }
</style>
@endpush

@push('scripts')
<script>
    jQuery(document).ready(function () {


        jQuery(document).on('click', '.product-image-list .is_main_image_button', function (e) {
            e.preventDefault();
            //jQuery(this).toggleClass('active');

            //x = this;

            //var mainImageSrc = jQuery(this).parents('.image-preview:first').find('img').attr('src');
            //jQuery('.top-header img').attr('src', mainImageSrc);

            //console.info(mainImageSrc);

            jQuery('.product-image-list .is_main_image_button').removeClass('active');
            jQuery('.product-image-list .is_main_image_hidden_field').val(0);


            if (jQuery(this).hasClass('active')) {

                jQuery(this).removeClass('active');
                jQuery(this).parents('.image-preview:first').find('.is_main_image_hidden_field').val(0);
            } else {
                jQuery(this).addClass('active');
                jQuery(this).parents('.image-preview:first').find('.is_main_image_hidden_field').val(1);
            }

        });
        jQuery(document).on('click', '.product-image-list .image-preview .destroy-image', function (e) {


            var token = jQuery('.product-image-element').attr('data-token');
            var path = jQuery(e.target).parents('.image-preview:first').find('.img-tag').attr('src');
            var data = {_token: token, path: path};
            jQuery.ajax({
                url: '{{ URL::to("/admin/product-image/delete")}}',
                data: data,
                type: 'post',
                success: function (response) {
                    if (response.success == true) {
                        jQuery(e.target).parents('.image-preview:first').remove();
                    }

                }
            })
        });
        jQuery('.product-image-element').change(function (e) {
            var files = e.target.files;

            if (files.length <= 0) {
                return;
            }

            var formData = new FormData();

            formData.append('_token', jQuery(e.target).attr('data-token'));
            for (var i = 0, file; file = files[i]; ++i) {
                formData.append('image', file);
            }

            var xhr = new XMLHttpRequest();
            xhr.open('POST', '{{ URL::to("/admin/product-image/upload") }}', true);
            xhr.onload = function (e) {
                if (this.status == 200) {

                    jQuery('.product-image-list').append(this.response);
                    if (jQuery('.product-image-list .image-preview').length == 1) {
                        jQuery('.product-image-list .image-preview .is_main_image_button').trigger('click');
                    }
                }
            };

            xhr.send(formData);

            jQuery(".product-image-element").val('');
        });

    });
</script>
@endpush

modules/mage2/ecommerce/resources/views/admin/product/card/seo.blade.php
@include('mage2-ecommerce::forms.text',['name' => 'meta_title','label' => 'Meta Title'])

@include('mage2-ecommerce::forms.textarea',['name' => 'meta_description','label' => 'Meta Description'])